### ISSUE TITLE
[rocketbank] Ошибка получения email от банка при регистрации устройства

### ISSUE THREAD

**Issue by jonny3D** [zenmoney/ZenPlugins#172]
Ошибка получения email от банка при регистрации устройства:
```
[java.lang.Object@76dd910] Необходимо привязать устройство...
[java.lang.Object@76dd910] Отправляем запрос на регистрацию устройства zenmoney_605a6e7e6dd90900000000********** (+79991234***)
[java.lang.Object@76dd910] Смс с кодом отправлено
[java.lang.Object@76dd910] Получили код
[java.lang.Object@76dd910] Подтвержден
[ZP] Exception: __ TypeError: Cannot read property 'email' of undefined
[ZP] Call stack:
TypeError: Cannot read property 'email' of undefined
    at verifyDevice (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/rocketbank/main.js:674:44)
    at registerDevice (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/rocketbank/main.js:643:9)
    at getDevice (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/rocketbank/main.js:577:24)
    at RocketBank.loadProfile (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/rocketbank/main.js:273:22)
    at RocketBank.sync (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/rocketbank/main.js:46:28)
    at main (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/rocketbank/main.js:9:30)
    at <anonymous>:1:1
```

**Comment by evictorov** [comment]
У меня синхронизация с Рокетбанком отвалилась где-то с июня 2019 - видимо, они поменяли что-то на своей стороне. Будет ли обновление плагина?
