### ISSUE TITLE
[Alfabank] Sync broken after adding credit card to alfabank account

### ISSUE THREAD

**Issue by TheElvenPath** [zenmoney/ZenPlugins#248]
После оформления кредитки и оплаты по ней - вечером не прошла синхронизация. Лог ниже. Мне видится проблема в том, что после оформления нужно было сразу провести синхронизацию, пока небыло операций, а после появления операций - они не находят соответствующей карты.

[error] scrape call rejected with [Error: Unhandled credit account named Счёт кредитной карты (see logs)] 
(1797ms)
[ZP] Exception: __ [RUE] Unhandled credit account named Счёт кредитной карты (see logs)
[ZP] Call stack:
Error: [RUE] Unhandled credit account named Счёт кредитной карты (see logs)
    at convertCreditApiAccount (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:52163:15)
    at toZenmoneyAccount (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:52185:21)
    at Array.map (native)
    at convertApiAccountsToAccountTuples (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:52190:31)
    at _callee$ (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:52591:135)
    at tryCatch (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:47676:40)
    at Generator.invoke [as _invoke] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:47910:22)
    at Generator.prototype.(anonymous function) [as next] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:47728:21)
    at step (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:52436:191)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank/index.js:52436:361

**Comment by erictheswift** [comment]
fixed
try again
