### ISSUE TITLE
[UkrSibBank] Ошибка подключения Android

### ISSUE THREAD

**Issue by apletnev** [zenmoney/ZenPlugins#299]
Зарегестрировался в приложении, пытаюсь подключить укрсиббанк. Ввожу логин и пароль, получаю ошибку, вот лог:
```
[log] call anonymous with args: { preferences: { password: '<string[18]>', login: '<string[10]>' },
  fromDate: Wed May 01 2019 00:00:00 GMT+0300 (EEST),
  toDate: null,
  isFirstRun: true }
[debug] request { method: 'POST',
  url: 'https://online.ukrsibbank.com/clientendpoint/burlap/',
  headers: 
   { 'mb-protocol-version': '0.5.0',
     'mb-app-version': '1.106.1',
     'Content-Type': 'application/gzip; charset=utf-8',
     'User-Agent': 'Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86_64 Build/MASTER)',
     Host: 'online.ukrsibbank.com',
     Connection: 'Keep-Alive',
     'Accept-Encoding': 'gzip' },
  body: 
   { __type: 'com.ukrsibbank.client.protocol.operation.StartOperationRequest',
     operationId: 'logIn',
     parameters: 
      [ { __type: 'com.ukrsibbank.client.protocol.operation.ParameterMto',
          id: 'capabilities',
          value: 
           { __type: 'com.ukrsibbank.client.protocol.authentication.AuthenticationCapabilitiesMto',
             capabilities: 
              { items: 
                 [ { __type: 'com.ukrsibbank.client.protocol.authentication.AuthenticationByTouchCapabilityMto',
                     enabled: false,
                     hasToken: false },
                   [length]: 1 ],
                itemType: 'com.ukrsibbank.client.protocol.authentication.AuthenticationCapabilityMto' } } },
        [length]: 1 ] } }
[debug] [Error: Assertion failed: Could not get response protocol version]
[debug] response { status: 200,
  url: 'https://online.ukrsibbank.com/clientendpoint/burlap/',
  headers: 
   { connection: 'keep-alive',
     'content-security-policy': '',
     'content-type': 'application/octet-stream',
     date: 'Sat, 04 May 2019 12:02:07 GMT',
     httprequestid: 'd39b3a54845342c6927f6e57014bbe80',
     server: 'WildFly/10',
     'set-cookie': '<string[340]>',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     'transfer-encoding': 'chunked',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-powered-by': 'Undertow/1',
     'x-xss-protection': '1; mode=block' },
  body: null,
  ms: 210 }
[debug] request { method: 'POST',
  url: 'https://online.ukrsibbank.com/clientendpoint/burlap/',
  headers: 
   { 'mb-protocol-version': '0.5.0',
     'mb-app-version': '1.106.1',
     'Content-Type': 'application/gzip; charset=utf-8',
     'User-Agent': 'Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86_64 Build/MASTER)',
     Host: 'online.ukrsibbank.com',
     Connection: 'Keep-Alive',
     'Accept-Encoding': 'gzip' },
  body: { __type: 'com.ukrsibbank.client.protocol.authentication.LogoutRequest' } }
[debug] [Error: Assertion failed: Could not get response protocol version]
[debug] response { status: 200,
  url: 'https://online.ukrsibbank.com/clientendpoint/burlap/',
  headers: 
   { connection: 'keep-alive',
     'content-security-policy': '',
     'content-type': 'application/octet-stream',
     date: 'Sat, 04 May 2019 12:02:07 GMT',
     httprequestid: '175b950f89434e139cbfc9d972da696a',
     server: 'WildFly/10',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     'transfer-encoding': 'chunked',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-powered-by': 'Undertow/1',
     'x-xss-protection': '1; mode=block' },
  body: null,
  ms: 50 }
[error] anonymous call rejected with [Error: Assertion failed: Could not get response from remote server] 
(320ms)
[ZP] Exception: __ [RUE] Assertion failed: Could not get response from remote server
[ZP] Call stack:
Error: [RUE] Assertion failed: Could not get response from remote server
    at Object.assert (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:572329)
    at Object.<anonymous> (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:580499)
    at v (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:524985)
    at Generator._invoke (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:524773)
    at Generator.e.(anonymous function) [as next] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:525164)
    at r (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:576897)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:576991
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:491931
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:491959
    at e.exports (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/ukrsibbank/index.js:1:544697)
```

**Comment by skvav** [comment]
Спасибо за сообщение о баге. Попробуйте, пожалкуйста, еще раз, внесли правки

**Comment by apletnev** [comment]
Спасибо, увы, пока что не работает. Правда теперь другая ошибка и не показывает логи. 
Из приложения укрсиббанка подключится могу, так же могу подключится через веб сайт.
![Screenshot_20190514-090431_Zenmoney](https://user-images.githubusercontent.com/220872/57674439-f8b62700-7627-11e9-806e-490e6cdbb30b.jpg)
Где можно посмотреть изменения которые вы делаете для укрсиббанк плагина? Похоже что его нет в этом репозитории. Спасибо

**Comment by skvav** [comment]
В открытом доступе лежат плагины, которые разрабатываются с помощью сообщества и не требуют дополнительных договоренностей с банками.
Выкатили правки, попробуйте, пожалуйста, еще раз.

**Comment by apletnev** [comment]
Здравствуйте. Теперь все работает. Спасибо, можно тикет закрывать.
