### ISSUE TITLE
[alfabank-by] Синхронизация не работает! Ошибка при обработке запроса

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#379]
При попытке настройки синхронизации с банком появляется сообщение "Произошла ошибка при обработке запроса".

```
[log] call anonymous with args: { preferences: { isResident: '<string[4]>' },
  fromDate: Sun Sep 01 2019 23:37:55 GMT+0300 (+03),
  toDate: null,
  isFirstRun: false }
[debug] request { method: 'POST',
  url: 'https://insync2.alfa-bank.by/mBank256/v6/CheckDeviceStatus?locale=ru',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'Content-Type': 'application/json; charset=UTF-8',
     'X-Client-App': 'Android/5.6.1',
     'User-Agent': 'okhttp/3.12.0' },
  body: { deviceId: '<string[36]>', locale: 'ru' } }
[debug] response { status: 200,
  url: 'https://insync2.alfa-bank.by/mBank256/v6/CheckDeviceStatus?locale=ru',
  headers:
   { 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
     'content-length': '89',
     'content-type': 'application/json;charset=UTF-8',
     date: 'Tue, 17 Sep 2019 08:47:33 GMT',
     expires: '0',
     pragma: 'no-cache',
     server: 'Apache-Coyote/1.1',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'DENY',
     'x-xss-protection': '1; mode=block' },
  body:
   { status: 'NEW',
     preAuthZone: false,
     timeout: 1500,
     isCredit: false },
  ms: 141 }
[debug] request { method: 'POST',
  url: 'https://insync2.alfa-bank.by/mBank256/v6/Authorization?locale=ru',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'Content-Type': 'application/json; charset=UTF-8',
     'X-Client-App': 'Android/5.6.1',
     'User-Agent': 'okhttp/3.12.0' },
  body:
   { deviceId: '<string[36]>',
     deviceName: 'ZenMoney Plugin',
     isResident: true,
     documentNum: '<string[14]>',
     issueDate: '<string[8]>',
     screenHeight: 1794,
     screenWidth: 1080 } }
[debug] response { status: 500,
  url: 'https://insync2.alfa-bank.by/mBank256/v6/Authorization?locale=ru',
  headers:
   { 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
     'content-length': '92',
     'content-type': 'application/json;charset=UTF-8',
     date: 'Tue, 17 Sep 2019 08:47:56 GMT',
     expires: '0',
     pragma: 'no-cache',
     server: 'Apache-Coyote/1.1',
     'x-cnection': 'close',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'DENY',
     'x-xss-protection': '1; mode=block' },
  body: { message: 'Произошла ошибка при обработке запроса' },
  ms: 129 }
[error] anonymous call rejected with { message: 'Ответ банка: Произошла ошибка при обработке запроса',
  stack: 'Error\n    at t.e (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:565038)\n    at new t (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:565424)\n    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:571372\n    at y (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:525123)\n    at Generator._invoke (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:524911)\n    at Generator.e.(anonymous function) [as next] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:525302)\n    at r (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:568537)\n    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:568631\n    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:492069\n    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:492097',
  fatal: false,
  allowRetry: true,
  toString:
   { [Function]
     [length]: 0,
     [name]: '',
     [prototype]: { [constructor]: [Circular] } } }
(23697ms)
[ZP] Exception: _R Ответ банка: Произошла ошибка при обработке запроса
[ZP] Call stack:
Error
    at t.e (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:565038)
    at new t (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:565424)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:571372
    at y (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:525123)
    at Generator._invoke (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:524911)
    at Generator.e.(anonymous function) [as next] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:525302)
    at r (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:568537)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:568631
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:492069
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:1:492097

**Comment by vetheslav** [comment]
@alparo тут таблетка: https://github.com/zenmoney/ZenPlugins/pull/381

**Comment by alparo** [comment]
Спасибо. Теперь работает.
