### ISSUE TITLE
Ошибка синхронизации с райффайзенбанком 75

### ISSUE THREAD

**Issue by Victorshm** [zenmoney/ZenPlugins#432]
С 17ого числа возникает ошибка при синхронизации
ZenPlugin [a5.9.0.400257] [raiffeisen 75] 
Отчёт на почту отправлен. 
Установлена последняя версия. 
Советы со страницы плагина не помогли.

> [error] anonymous call rejected with [Error: Assertion failed: non-successful response] 
(239ms)
[ZP] Exception: __ [RUE] Assertion failed: non-successful response
[ZP] Call stack:
Error: [RUE] Assertion failed: non-successful response
    at Object.assert (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:566927)
    at p (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:580688)
    at Object.<anonymous> (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:582499)
    at y (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:525122)
    at Generator._invoke (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:524910)
    at Generator.e.(anonymous function) [as next] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:525301)
    at r (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:580513)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:580607
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:492068
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:492096

>

**Comment by kkorsakov** [comment]
Аналогично, сломалось совсем

**Comment by aleximos** [comment]
Аналогично, ошибку отправил на support.

**Comment by PavelKolpakov** [comment]
у меня немного другая ошибка. При добавлении райфа:
[error] anonymous call rejected with [Error: Assertion failed: unexpected card 
[ZP] Exception: __ [RUE] Assertion failed: unexpected card
    at Object.assert (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:820842)
    at t.a (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:830494)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:834929
    at v (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:775157)
    at Generator._invoke (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:774945)
    at Generator.e.(anonymous function) [as next] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:775336)
    at r (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:833691)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:833785
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:742103
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/raiffeisen/index.js:1:742131

**Comment by andrey-makhnutin** [comment]
Попробуйте обновить приложение в Google Play и переподключить синхронизацию.
У меня заработало, хотя плагин raiffeisen из этого репозитория удалён (!) #430

**Comment by PavelKolpakov** [comment]
вчера вечером также заработало без обновления приложения даже

**Comment by kkorsakov** [comment]
теперь все траты стали отображаться как корректировки

**Comment by skvav** [comment]
@kkorsakov а пришлите пожалуйста лог с указанием по какой карте/счету не загружаются операции.
