### ISSUE TITLE
[belgazprombank] TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#456]
Перестала работать синхронизация. Вот выдержки из логов:

```
[log] call anonymous with args: { preferences: { password: '<string[20]>', login: '<string[8]>' },
  fromDate: Mon Nov 25 2019 17:12:58 GMT+0300 (+03),
  toDate: null,
  isFirstRun: false }

...

[log] >>> Загружено 8 операций.
[error] anonymous call rejected with [TypeError: Cannot read property 'slice' of null]
(4643ms)
[ZP] Exception: __ TypeError: [RUE] Cannot read property 'slice' of null
[ZP] Call stack:
TypeError: [RUE] Cannot read property 'slice' of null
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:586825
    at Object.t.d (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:586934)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:592457
    at Array.map (native)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:592432
    at y (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:525116)
    at Generator._invoke (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:524904)
    at Generator.e.(anonymous function) [as next] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:525295)
    at r (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:591832)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/bgpb/index.js:1:591926
```

**Comment by alparo** [comment]
Похоже, проблема пропала. Понаблюдаю пару дней, а потом закрою тикет.
